---
- name: Install Nginx
  hosts: lighthouse
  handlers:
  - name: Start nginx
    become: true
    service:
      name: nginx
      state: restarted
  tasks:
    - name: Add repo
      become: true
      yum_repository:
        name: nginx
        description: NGINX repos
        baseurl: "https://nginx.org/packages/mainline/centos/8/x86_64/"
        gpgcheck: no
    - name: Nginx install
      become: true
      yum:
        name: nginx
        state: present
#        notify: start-nginx
- name: Install Lighthouse
  hosts: lighthouse
  tasks:
    - name: Git install
      become: true
      yum:
        name: git
    - name: Get lighthouse
      git:
        repo: https://github.com/VKCOM/lighthouse.git
        version: master
        dest: ./lighthouse
      register: copy_remote
    - name: Copy config
      template: 'src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=0664'
      become: true
- name: Install Vector
  hosts: vector
  tasks:
    - name: Get vector distrib
      get_url:
        validate_certs: false
        url: https://packages.timber.io/vector/0.24.0/vector-0.24.0-1.x86_64.rpm
        dest: ./vector-0.24.0.rpm
    - name: Install vector
      become: true
      yum:
        disable_gpg_check: yes
        name:
          - vector-0.24.0.rpm
    - name: Copy config
      become: true
      template: 'src=vector.j2 dest=/etc/vector/vector.toml owner=root group=root mode=0664'
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
      - name: Get clickhouse distrib
        get_url:
          validate_certs: false
          url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
          dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
        with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          get_url:
            validate_certs: false
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      yum:
        disable_gpg_check: yes
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
