---
- name: Install Nginx
  hosts: lighthouse
  roles:
    - nginx-role

- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - lighthouse-role

- name: Install Vector
  hosts: vector
  roles:
    - vector-role

- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse-role

