apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-and-multitools-deployment
  labels:
    app: nginx-mt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-mt
  template:
    metadata:
      labels:
        app: nginx-mt
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.5
        ports:
        - containerPort: 80
      - name: multitools
        image: praqma/network-multitool:alpine-extra
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-and-multitools
spec:
  selector:
    app: nginx-mt
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080